# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# clear all permissions for GITHUB_TOKEN
permissions: {}

jobs:
  initial-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Checkout maven
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/cached
          key: maven-${{ runner.os }}-initial-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-initial-
            maven-${{ runner.os }}-

      - name: Set up Maven
        shell: bash
        run: mvn --errors --batch-mode --show-version org.apache.maven.plugins:maven-wrapper-plugin:3.3.2:wrapper "-Dmaven=4.0.0-beta-4"

      - name: Build Maven distributions
        shell: bash
        run: ./mvnw verify -e -B -V -DdistributionFileName=apache-maven -Dmaven.repo.local=$HOME/.m2/repository/cached

      - name: List contents of target directory
        shell: bash
        run: ls -la apache-maven/target

      - name: Upload Maven distributions
        uses: actions/upload-artifact@v4
        with:
          name: maven-distributions
          path: |
            apache-maven/target/apache-maven*.zip
            apache-maven/target/apache-maven*.tar.gz

  full-build:
    needs: initial-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: ['17']
    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Install Graphviz (MacOS)
        if: runner.os == 'macOS'
        run: brew install graphviz

      - name: Install Graphviz (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get install graphviz

      - name: Install Graphviz (Windows)
        if: runner.os == 'Windows'
        run: choco install graphviz

      - name: Checkout maven
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download Maven distribution
        uses: actions/download-artifact@v4
        with:
          name: maven-distributions
          path: maven-dist

      - name: List downloaded files
        shell: bash
        run: ls -la maven-dist

      - name: Extract Maven distribution
        shell: bash
        run: |
          mkdir -p maven-local
          if [ "${{ runner.os }}" = "Windows" ]; then
            unzip maven-dist/apache-maven-bin.zip -d maven-local
          else
            tar xzf maven-dist/apache-maven-bin.tar.gz -C maven-local --strip-components 1
          fi
          echo "MAVEN_HOME=$PWD/maven-local" >> $GITHUB_ENV
          echo "$PWD/maven-local/bin" >> $GITHUB_PATH

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/cached
          key: maven-${{ runner.os }}-full-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-full-
            maven-${{ runner.os }}-

      - name: Build site with downloaded Maven
        shell: bash
        run: mvn verify site -e -B -V -Preporting -Dmaven.repo.local=$HOME/.m2/repository/cached

  integration-tests:
    needs: initial-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: ['17']
    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Checkout maven
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download Maven distribution
        uses: actions/download-artifact@v4
        with:
          name: maven-distributions
          path: maven-dist

      - name: List downloaded files
        shell: bash
        run: ls -la maven-dist

      - name: Extract Maven distribution
        shell: bash
        run: |
          mkdir -p maven-local
          if [ "${{ runner.os }}" = "Windows" ]; then
            unzip maven-dist/apache-maven-bin.zip -d maven-local
            # Get the name of the extracted directory
            MAVEN_DIR=$(ls maven-local)
            # Move contents up one level
            mv "maven-local/$MAVEN_DIR"/* maven-local/
            rm -r "maven-local/$MAVEN_DIR"
          else
            tar xzf maven-dist/apache-maven-bin.tar.gz -C maven-local --strip-components 1
          fi
          echo "MAVEN_HOME=$PWD/maven-local" >> $GITHUB_ENV
          echo "$PWD/maven-local/bin" >> $GITHUB_PATH

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/cached
          key: maven-${{ runner.os }}-its-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-its
            maven-${{ runner.os }}-

      - name: Run integration tests
        shell: bash
        run: mvn install -e -B -V -Prun-its,embedded -Dmaven.repo.local=$HOME/.m2/repository/local -Dmaven.repo.local.tail=$HOME/.m2/repository/cached

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ github.run_number }}-integration-test-artifact-${{ runner.os }}-${{ matrix.java }}
          path: ./its/core-it-suite/target/test-classes/
          
  build-on-z:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build on s390x arch 
      run: |
        sudo docker run --rm --privileged tonistiigi/binfmt:qemu-v6.1.0
    - name: Run build 
      uses: uraimo/run-on-arch-action@v2.8.1
      with:
        arch: s390x
        distro: ubuntu22.04
        run: | 
         apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y wget tar curl sudo
         curl -SL -o temurin_runtime.tar.gz  https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.7%2B7/OpenJDK17U-jdk_s390x_linux_hotspot_17.0.7_7.tar.gz
         sudo mkdir -p /opt/java
         sudo tar -zxvf temurin_runtime.tar.gz -C /opt/java --strip-components 1
         rm -rf temurin_runtime.tar.gz
         export JAVA_HOME=/opt/java
         java -version
         wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.8/apache-maven-3.8.8-bin.tar.gz 
         tar -xzf apache-maven-3.8.8-bin.tar.gz  
         export PATH=`pwd`/apache-maven-3.8.8/bin/:$PATH
         mvn --errors --batch-mode --show-version org.apache.maven.plugins:maven-wrapper-plugin:3.3.2:wrapper "-Dmaven=4.0.0-beta-4"
         ./mvnw verify -e -B -V
         ls -la apache-maven/target
         sudo apt-get install graphviz
         mvn verify site -e -B -V -Preporting
         mvn install -e -B -V -Prun-its,embedded
